name: test-all-Ubuntu
on:
  push:
    paths-ignore:
    - 'docs/**'
  pull_request:
    types: [opened, ready_for_review, review_requested]
    paths-ignore:
    - 'docs/**'
  workflow_dispatch:
  
jobs:
  test-bionic:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: ENVIRONMENT=testing && LIBRETIME_LOG_DIR=/tmp/log/libretime
      - run: sudo bash ./.github/scripts/install-bionic.sh
      - run: sudo bash ./.github/scripts/init-postgres.sh
      - run: sudo composer install
      - run: cd airtime_mvc/tests && sudo bash ../../vendor/bin/phpunit && cd ../..
      - run: sudo bash ./.github/scripts/python-pkg-install.sh
      - run: sudo bash ./.github/scripts/python-pkg-test.sh
  # test-xenial:
  #   runs-on: ubuntu-16.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.5'
  #     - run: ENVIRONMENT=testing && LIBRETIME_LOG_DIR=/tmp/log/libretime
  #     - run: sudo bash ./.github/scripts/install.sh
  #     - run: sudo composer install
  #     - run: sudo bash ./.github/scripts/python-pkg-install.sh
  #     - run: sudo bash ./.github/scripts/python-pkg-test.sh
